title: 5 Steps for Racial Justice in Artificial Life
logo: /assets/img/logo.png
description: The Emerging Researchers in Artificial Life (ERA) is the official student, post-doc, and junior researcher group for the International Society for Artificial Life (ISAL).
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
