title: Essential Actions in Artificial Life
logo: /assets/img/logo.png
description: 5 steps the Artificial Life community can take towards racial justice in our community.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
